### ISSUE TITLE
Any chance you can release the BiasedMNIST before NeurIPS 2021 deadline?

### ISSUE THREAD

**Issue by vihari** [erobic/bias-mitigators#1]

**Comment by erobic** [comment]
Hi, 

I pushed the version of the dataset used in the paper to 'tmp' branch (biased_mnist_dataset.py has the function to generate it). However, we are still iterating on the dataset and the results in the paper will likely change. Furthermore, if the dataset is updated, this current version will no longer be supported.

Thank you!
